version: '3.4'

services:
    authentication_service:
        container_name: authentication_service
        image: authentication_service:latest
        restart: unless-stopped
        network_mode: "host" # communication to arete testing service
        build:
            context: .
        env_file:
            - .env
        environment:
            ADMIN_PASS: ${ADMIN_PASS:-admin}
            LOG_LEVEL: ${DATABASE_PASSWORD:-warn}
            DATABASE_MIGRATION: ${DATABASE_MIGRATION:-update} # options are create-drop, update, create
            DATABASE_PASSWORD: ${DATABASE_PASSWORD:-v1jXKUpcHAm0dc3C2GNlFkjibEwzdkTbG0Vnld5RZ16Nriz86hQ0cQ2dC09lpVjg}
        ports:
            - "8001:8001"
