version: '3.4'

services:

  authentication_service:
    container_name: authentication_service
    image: authentication_service:latest
    restart: unless-stopped
    network_mode: "host" # communication to arete testing service
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8001:8001"
