version: '3.4'

services:

  arete_ui_back_db:
    container_name: postgres_arete_ui
    image: postgres:11.5
    restart: unless-stopped
    environment:
      POSTGRES_USER: arete
      POSTGRES_DB: arete
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-v1jXKUpcHAm0dc3C2GNlFkjibEwzdkTbG0Vnld5RZ16Nriz86hQ0cQ2dC09lpVjg}
    ports:
      - "5433:5432"

  arete_ui_adminer:
    container_name: adminer_arete_ui
    image: adminer
    restart: unless-stopped
    ports:
      - "8190:8080"

  arete_ui_back:
    container_name: arete_ui_back
    image: arete_ui_back:latest
    restart: unless-stopped
    network_mode: "host" # communication to arete testing service
    build:
      context: .
    env_file:
      - ..env #Change to .env to run locally
    environment:
      SHARED_SECRET: ${SHARED_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - arete_ui_back_db
    ports:
      - "8001:8001"